// <auto-generated />
using EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BloggingDbContext))]
    [Migration("20201110203322_SchoolDb")]
    partial class SchoolDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkCore.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Student 1"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Student 2"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Student 3"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Student 4"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Student 5"
                        },
                        new
                        {
                            StudentId = 6,
                            Name = "Student 6"
                        },
                        new
                        {
                            StudentId = 7,
                            Name = "Student 7"
                        },
                        new
                        {
                            StudentId = 8,
                            Name = "Student 8"
                        },
                        new
                        {
                            StudentId = 9,
                            Name = "Student 9"
                        },
                        new
                        {
                            StudentId = 10,
                            Name = "Student 10"
                        },
                        new
                        {
                            StudentId = 11,
                            Name = "Student 11"
                        },
                        new
                        {
                            StudentId = 12,
                            Name = "Student 12"
                        },
                        new
                        {
                            StudentId = 13,
                            Name = "Student 13"
                        },
                        new
                        {
                            StudentId = 14,
                            Name = "Student 14"
                        },
                        new
                        {
                            StudentId = 15,
                            Name = "Student 15"
                        },
                        new
                        {
                            StudentId = 16,
                            Name = "Student 16"
                        },
                        new
                        {
                            StudentId = 17,
                            Name = "Student 17"
                        },
                        new
                        {
                            StudentId = 18,
                            Name = "Student 18"
                        },
                        new
                        {
                            StudentId = 19,
                            Name = "Student 19"
                        },
                        new
                        {
                            StudentId = 20,
                            Name = "Student 20"
                        },
                        new
                        {
                            StudentId = 21,
                            Name = "Student 21"
                        },
                        new
                        {
                            StudentId = 22,
                            Name = "Student 22"
                        },
                        new
                        {
                            StudentId = 23,
                            Name = "Student 23"
                        },
                        new
                        {
                            StudentId = 24,
                            Name = "Student 24"
                        },
                        new
                        {
                            StudentId = 25,
                            Name = "Student 25"
                        },
                        new
                        {
                            StudentId = 26,
                            Name = "Student 26"
                        },
                        new
                        {
                            StudentId = 27,
                            Name = "Student 27"
                        },
                        new
                        {
                            StudentId = 28,
                            Name = "Student 28"
                        },
                        new
                        {
                            StudentId = 29,
                            Name = "Student 29"
                        },
                        new
                        {
                            StudentId = 30,
                            Name = "Student 30"
                        },
                        new
                        {
                            StudentId = 31,
                            Name = "Student 31"
                        },
                        new
                        {
                            StudentId = 32,
                            Name = "Student 32"
                        },
                        new
                        {
                            StudentId = 33,
                            Name = "Student 33"
                        },
                        new
                        {
                            StudentId = 34,
                            Name = "Student 34"
                        },
                        new
                        {
                            StudentId = 35,
                            Name = "Student 35"
                        },
                        new
                        {
                            StudentId = 36,
                            Name = "Student 36"
                        },
                        new
                        {
                            StudentId = 37,
                            Name = "Student 37"
                        },
                        new
                        {
                            StudentId = 38,
                            Name = "Student 38"
                        },
                        new
                        {
                            StudentId = 39,
                            Name = "Student 39"
                        },
                        new
                        {
                            StudentId = 40,
                            Name = "Student 40"
                        },
                        new
                        {
                            StudentId = 41,
                            Name = "Student 41"
                        },
                        new
                        {
                            StudentId = 42,
                            Name = "Student 42"
                        },
                        new
                        {
                            StudentId = 43,
                            Name = "Student 43"
                        },
                        new
                        {
                            StudentId = 44,
                            Name = "Student 44"
                        },
                        new
                        {
                            StudentId = 45,
                            Name = "Student 45"
                        },
                        new
                        {
                            StudentId = 46,
                            Name = "Student 46"
                        },
                        new
                        {
                            StudentId = 47,
                            Name = "Student 47"
                        },
                        new
                        {
                            StudentId = 48,
                            Name = "Student 48"
                        },
                        new
                        {
                            StudentId = 49,
                            Name = "Student 49"
                        },
                        new
                        {
                            StudentId = 50,
                            Name = "Student 50"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.StudentSubject", b =>
                {
                    b.Property<int>("StudentSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("subjectScore")
                        .HasColumnType("int");

                    b.HasKey("StudentSubjectId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");

                    b.HasData(
                        new
                        {
                            StudentSubjectId = 1,
                            StudentId = 1,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 2,
                            StudentId = 1,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 3,
                            StudentId = 2,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 4,
                            StudentId = 2,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 5,
                            StudentId = 3,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 6,
                            StudentId = 3,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 7,
                            StudentId = 4,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 8,
                            StudentId = 4,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 9,
                            StudentId = 5,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 10,
                            StudentId = 5,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 11,
                            StudentId = 6,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 12,
                            StudentId = 6,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 13,
                            StudentId = 7,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 14,
                            StudentId = 7,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 15,
                            StudentId = 8,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 16,
                            StudentId = 8,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 17,
                            StudentId = 9,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 18,
                            StudentId = 9,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 19,
                            StudentId = 10,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 20,
                            StudentId = 10,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 21,
                            StudentId = 11,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 22,
                            StudentId = 11,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 23,
                            StudentId = 12,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 24,
                            StudentId = 12,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 25,
                            StudentId = 13,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 26,
                            StudentId = 13,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 27,
                            StudentId = 14,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 28,
                            StudentId = 14,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 29,
                            StudentId = 15,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 30,
                            StudentId = 15,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 31,
                            StudentId = 16,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 32,
                            StudentId = 16,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 33,
                            StudentId = 17,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 34,
                            StudentId = 17,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 35,
                            StudentId = 18,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 36,
                            StudentId = 18,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 37,
                            StudentId = 19,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 38,
                            StudentId = 19,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 39,
                            StudentId = 20,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 40,
                            StudentId = 20,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 41,
                            StudentId = 21,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 42,
                            StudentId = 21,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 43,
                            StudentId = 22,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 44,
                            StudentId = 22,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 45,
                            StudentId = 23,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 46,
                            StudentId = 23,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 47,
                            StudentId = 24,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 48,
                            StudentId = 24,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 49,
                            StudentId = 25,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 50,
                            StudentId = 25,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 51,
                            StudentId = 26,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 52,
                            StudentId = 26,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 53,
                            StudentId = 27,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 54,
                            StudentId = 27,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 55,
                            StudentId = 28,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 56,
                            StudentId = 28,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 57,
                            StudentId = 29,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 58,
                            StudentId = 29,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 59,
                            StudentId = 30,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 60,
                            StudentId = 30,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 61,
                            StudentId = 31,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 62,
                            StudentId = 31,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 63,
                            StudentId = 32,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 64,
                            StudentId = 32,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 65,
                            StudentId = 33,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 66,
                            StudentId = 33,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 67,
                            StudentId = 34,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 68,
                            StudentId = 34,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 69,
                            StudentId = 35,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 70,
                            StudentId = 35,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 71,
                            StudentId = 36,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 72,
                            StudentId = 36,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 73,
                            StudentId = 37,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 74,
                            StudentId = 37,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 75,
                            StudentId = 38,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 76,
                            StudentId = 38,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 77,
                            StudentId = 39,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 78,
                            StudentId = 39,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 79,
                            StudentId = 40,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 80,
                            StudentId = 40,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 81,
                            StudentId = 41,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 82,
                            StudentId = 41,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 83,
                            StudentId = 42,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 84,
                            StudentId = 42,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 85,
                            StudentId = 43,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 86,
                            StudentId = 43,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 87,
                            StudentId = 44,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 88,
                            StudentId = 44,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 89,
                            StudentId = 45,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 90,
                            StudentId = 45,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 91,
                            StudentId = 46,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 92,
                            StudentId = 46,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 93,
                            StudentId = 47,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 94,
                            StudentId = 47,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 95,
                            StudentId = 48,
                            SubjectId = 3,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 96,
                            StudentId = 48,
                            SubjectId = 4,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 97,
                            StudentId = 49,
                            SubjectId = 1,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 98,
                            StudentId = 49,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 99,
                            StudentId = 50,
                            SubjectId = 2,
                            subjectScore = 0
                        },
                        new
                        {
                            StudentSubjectId = 100,
                            StudentId = 50,
                            SubjectId = 3,
                            subjectScore = 0
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "subj 1"
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "subj 2"
                        },
                        new
                        {
                            SubjectId = 3,
                            Name = "subj 3"
                        },
                        new
                        {
                            SubjectId = 4,
                            Name = "subj 4"
                        },
                        new
                        {
                            SubjectId = 5,
                            Name = "subj 5"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.StudentSubject", b =>
                {
                    b.HasOne("EntityFrameworkCore.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkCore.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
